[package]
name = "spield-wrapper"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
spield-shared = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
blend-contract-sdk = { workspace = true, features = ["testutils"] }
sep-40-oracle = { version = "=1.4.0", features = ["testutils"] }
spield-strategy = { path = "../strategy" }
